### ISSUE TITLE
Wont work in atmel studio

### ISSUE THREAD

**Issue by rharrison** [lucullusTheOnly/TinyWire#13]
So I have this working fine in the arduino ide but when i move to Atmel studio and compile it wont work even though it compiles and uploads with no errors. This is using an atTiny85 with F_CPU=1000000L in Atmel Studio. Any thoughts from those cleverer than me?

TIA 

Robert

**Comment by lucullusTheOnly** [comment]
How does it not work? Can you check, what actually happens by adding a live signal and maybe some indicators to check, where exactly the problem happens? That would make it drastically easier to find the problem.

Did it work with a clock speed of 1MHz when using the Arduino IDE?

**Comment by lucullusTheOnly** [comment]
I'm closing this issue, as it's unlikely to get further information 2 years after the opening of the issue
