### ISSUE TITLE
Having one Arduino as Master in one i2C bis and Slave in a Second I2C Bus 

### ISSUE THREAD

**Issue by fannta1990** [lucullusTheOnly/TinyWire#20]
Hi everyone! 

I am building a circuit using an Arduino feather as a Master and several Arduino Gemma’s (who tun with TinyWire instead of normal Wire) as a slave in the I2C bus. This works fine. Now however, I want to Bild an ondividual i2C connection from every Gemma in which it should act as a Master to send out commands. 

I have not been able to figure out how to create a virtual second wire using the Arduino Gemma as a Master in a second i2C bus. 

It it possible to do so using the tinywire library? Or does a virtual tiny wire library exist?! 

Thanks for your help!

**Comment by lucullusTheOnly** [comment]
Hello,

The TinyWire library uses the ATtiny's USI (Universal Serial Interface) hardware. So this library can only be used once for every Gemma. It is not a pure software I2C library. So unfortunately you cannot use it.

Maybe you can get what you need with the [SoftI2CMaster library](https://github.com/felias-fogg/SoftI2CMaster). Keep in mind, that the ATtiny85 does not have much RAM and flash, so you might run out of them. In that case, you should reconsider your project topology and the involved interfaces.

Good luck with building your project!
